
export const SUCCESS = "SUCCESS"

export const FAILURE = "FAILURE"

export const FETCH_DB_POSTS = "FETCH_DB_POSTS"

export const REMOVE_DB_POSTS = "REMOVE_DB_POSTS"

export const FETCH_POST_COMMENTS = "FETCH_POST_COMMENTS"

export const REMOVE_POST_COMMENTS = "REMOVE_POST_COMMENTS"